namespace Neogov.Core.Common.Enums
{
    //TODO - Use T4 Template
    public enum EntityIdType : int
    {
        None = 0,
        Employee = 1,
        Evaluation = 2,
        DevelopmentPlan = 3,
        Goal = 4,
        GoalCategory = 5,
        Competency = 6,
        CompetencyGroup = 7,
        CompetencyCategory = 8,
        Position = 9,
        PerformanceSchedule = 10,
        Department = 11,
        Division = 12,
        ClassSpecification = 13,
        RatingScale = 14,
        WritingAssistant = 15,
        User = 16,
        Training = 17,
        TrainingCategory = 18,
        Report = 19,
        EmployeeGroup = 20,
        EvaluationTemplate = 21,
        ClassSpecificationGroup = 22,
        GoalGroups = 23,
        Task = 24,
        Rater = 25,
        Approver = 26,
        TemplateRater = 27,
        ApprovalStep = 28,
        CustomObjectsTemplate = 29,
        CustomObjectsData = 30,
        TemplateChecklistItem = 31,
        OnboardingTask = 32,
        OnboardingForm = 33,
        EvaluationTemplateTask = 34,
        TestManagementSystem = 35,
        TMSOwner = 36,
        TMSAssignee = 37,
        Job = 38,
        TemplateAcknowledger = 39,
        EvaluationContentSection = 40,
        Question = 41,
        Portal = 42,
        SecurityProfile = 43,
        DepartmentHead = 44,
        Checklist = 45,
        EvaluationNote = 46
    }
}